<?php

/**
 * Texto largo para la página Historia (hermandad/historia), resumen del libro TEXTO pdf.pdf.
 * Imágenes: public/assets/img/historia/*.jpg (archivo en B/N, ilustrativas).
 */

return [
    'title' => [
        'es' => 'Historia de la Hermandad',
        'en' => 'History of the Brotherhood',
    ],
    'content' => [
        'es' => <<<'HTML'
<h2>Orígenes en el barrio de San Pedro (1982–1983)</h2>
<figure class="historia-foto">
<img src="/assets/img/historia/decada-1980.jpg" alt="Ambiente urbano y años ochenta, imagen de archivo" loading="lazy" decoding="async" />
<figcaption>Imagen de archivo en blanco y negro. El proyecto cofrade nace del diálogo entre vecinos, comercio y parroquia en un barrio que reclamaba más comunidad y atención social.</figcaption>
</figure>
<p>La historia que aquí se resume toma como fuente la crónica manuscrita y las actas que recogen el nacimiento de la Hermandad en torno a la <strong>Parroquia de San Pedro</strong>. Prácticamente el germen aparece en la calle Santa Isabel, pero es en la <strong>joyería de Martín Franco</strong>, en la calle San Pedro, donde en <strong>1982</strong> se fragua con fuerza la idea de una cofradía propia del barrio. Manuel Guerrero, sin vínculos previos con la zona, entabla conversaciones con el <strong>Padre Galindo</strong> y con José Serván, preocupados por el abandono y las carencias sociales del entorno, inspirándose en experiencias de mejora vecinal como las de la Atunara. El párroco exige, como condición, <strong>acercar a los vecinos a la Iglesia</strong> y tejer una comunidad sólida.</p>
<p>En la joyería se suceden las reuniones; de ellas surge un grupo comprometido —entre otros, María del Carmen Rubira, Martín Franco, Antonio Rubira Urbano, José Serván, Pedro Olmo Morales, Francisco Trujillo y Manuel Guerrero— que acuerda impulsar la cofradía. La junta parroquial, al principio, duda del proyecto. Las líneas maestras apuntan a una <strong>organización religiosa</strong> con fuerte impronta <strong>social y cultural</strong>: un núcleo de 22 personas (18 hombres y 4 mujeres) con Manuel Guerrero como coordinador, Antonio Rubira de tesorero y Francisco Trujillo de secretario. Se baraja traer la Hermandad de la Oración en el Huerto; la parroquia no ve con buenos ojos duplicar devociones y el camino se orienta a una identidad propia.</p>
<p>Un episodio memorable es el <strong>Jueves Santo de 1983</strong>: el Señor del Gran Poder debía visitar San Pedro en el marco de la obra de teatro <em>La Pasión</em>, con amplia participación juvenil y el apoyo del Hermano Mayor del Gran Poder, don Emilio de Villar. El <strong>parte de un zanco</strong> impide la entrada del Señor en el templo; el barrio, engalanado, queda con la esperanza encendida. Esa noche corre la palabra: los vecinos quieren <strong>una cofradía que transite sus calles</strong>. El grupo ya colabora con Cáritas y el <strong>Sábado Santo</strong> Serván y Guerrero exponen al párroco un plan integral —religioso, social y cultural— tomando referentes como José Ramón Mata Jiménez en la Atunara. El <strong>4 de abril de 1983</strong> se fijan bases fundacionales en un manuscrito de Manuel Guerrero Sigler, con asistencia del párroco don José Luis Galindo Martínez y los fundadores citados.</p>
<h2>Primera imagen, advocaciones y autorización diocesana</h2>
<figure class="historia-foto">
<img src="/assets/img/historia/parroquia-barrio.jpg" alt="Iglesia y entorno urbano, imagen de archivo" loading="lazy" decoding="async" />
<figcaption>Imagen de archivo. El templo y el barrio son el escenario donde se articula culto, solidaridad y salida a la calle.</figcaption>
</figure>
<p>Para dar culto público hace falta una imagen. La <strong>familia Gabaldón</strong> cede a la parroquia una Dolorosa, antes advocada a la Amargura; se acuerda el nombre de <strong>La Dolorosa de San Pedro</strong>, ligando la devoción al territorio. Tras debates y votación libre, el título de la hermandad se orienta a <strong>Jesús del Perdón y Nuestra Señora del Mayor Dolor</strong>, con la salvedad de que la advocación mariana coincide con la del Abandono en la ciudad, lo que obligará más adelante a afinar la denominación. Gestiones ante <strong>Junta de Hermandades, arcipreste y Obispado de Cádiz</strong> culminan el <strong>3 de junio de 1983</strong> con la <strong>autorización eclesiástica</strong> para la Asociación Parroquial y el acta prefundacional.</p>
<p>Tres días después constituye sesión la <strong>Junta Gestora</strong> (Manuel Guerrero, Antonio Rubira, Ramón Jiménez, Roberto Martín, Juan Mendoza, Daniel Moreno, Francisco Trujillo, José Gómez, Juan Carlos Borrego, Salvador Ramos y Salvador Hoyos), definiendo cargos: párroco director, coordinador Manolo Guerrero, secretaría, tesorería, representación parroquial y responsables. En julio se abordan la cesión en depósito de la Virgen, la <strong>primera Semana Cultural</strong> (octubre), la lotería de Navidad y el nombramiento de Manuel Guerrero al frente de la asociación. Las <strong>cuotas</strong> arrancan a 50 y 100 pesetas; el censo crece de 120 a 160 hermanos; en agosto de 1983 se fija el nombre <strong>Dolorosa de San Pedro</strong> para no chocar con el Abandono. Se imprimen <strong>10.000 estampas</strong> —pagadas por Martín Franco— repartidas solo en el barrio tras la Semana Santa de 1983.</p>
<p>El <strong>consejo parroquial</strong> impone para la primera salida condiciones penitenciales estrictas: mayoría de edad, sin insignias, junta con antifaz, salida nocturna, máximo cuatro horas, itinerario preferente por el barrio, autorización obispal si se sale de San Pedro, <strong>Rosario, Vía Crucis, sin música y máxima austeridad</strong>. Los fundadores ya piensan en el futuro paso de misterio del Cristo del Perdón.</p>
<h2>Semana Cultural, bendición de la Dolorosa y encargo del Señor</h2>
<p>Del <strong>3 al 9 de octubre de 1983</strong> la hermandad organiza la primera <strong>Semana Cultural</strong> del barrio: teatro, bailes, charlas, concursos y ofrenda floral a la Virgen. Acude el obispo <strong>don Antonio Dorado Soto</strong>. El <strong>domingo 9</strong> se bendice la <strong>Dolorosa de San Pedro</strong> (advocación aprobada el 30 de agosto), con niños en traje andaluz. La hermandad encarga un <strong>manto de terciopelo azul con encaje dorado</strong> siguiendo criterios de las Agustinas Recoletas de Chiclana. El <strong>15 de septiembre</strong> de 1983 la Virgen sale por primera vez en <strong>Rosario de la Aurora</strong>, en parihuela cedida por la cofradía del Viernes Santo, con gran participación del barrio.</p>
<p>En 1984 el proyecto del <strong>misterio del Perdón</strong> se encamina: presupuesto de 400.000 pesetas para la talla del Cristo que hoy procesiona —<strong>Nuestro Padre Jesús del Perdón en su tercera caída</strong>, con la Verónica y Simón de Cirene—. Tras votación de hermanos, gana el boceto en barro de <strong>Manuel Hernández León</strong>. En marzo de 1984 se celebran votaciones internas con 173 hermanos; las mujeres votan pero aún no procesionan ni forman parte de la asociación parroquial —situación que cambiará en 1987 con las normas diocesanas. La <strong>junta pro-cultos</strong> incorpora asesoras y el <strong>Grupo Joven</strong> (Isabel Trujillo, Inmaculada González), impulsando obra social: refuerzo escolar, costura, ayudas a familias, convenios con colegios Simón Abril y Santa Ana. Los presupuestos dedican más del <strong>70&nbsp;% a obra social</strong>; cinco hermanos atienden a diario las necesidades del barrio junto a Cáritas.</p>
<p>El <strong>contrato con Hernández León</strong> se firma en mayo de 1984; sucesivos pagos y campañas entre vecinos financian la obra. Se construye <strong>altar de mármol para la Virgen</strong> y se refuerza la colaboración con Cáritas. En 1985 llega el Cristo envuelto en sábanas desde Sevilla en una furgoneta del estanco San Pedro; se bendice el <strong>23 de marzo de 1985</strong>, con sencillez deliberada, apadrinado por Domingo López y esposa. El <strong>2 de abril de 1985</strong>, <strong>Jueves Santo</strong>, sale por primera vez el Señor en andas cedidas por la Borriquita, con <strong>70 nazarenos</strong> en túnica crema, antifaz morado y cíngulo de esparto, <strong>cruz de guía tosca</strong>, dos tambores, Rosario rezado y lluvia que algunos llaman “bendición”. La Dolorosa acompaña en parihuela de la Soledad. Ese año nace el <strong>primer cartel de Semana Santa</strong> de la hermandad —el primero de la ciudad con cartel propio— y la salida cierra con saldo positivo. La hermandad envía <strong>Estatutos</strong> al Obispado; en julio de 1985 se autoriza la junta pro-cultos del Santísimo Cristo del Perdón y Nuestra Señora Dolorosa.</p>
<h2>Estatutos, salidas, paso de misterio y vida cofrade (1986–1989)</h2>
<figure class="historia-foto">
<img src="/assets/img/historia/procesion.jpg" alt="Procesión y calles, imagen de archivo" loading="lazy" decoding="async" />
<figcaption>Imagen de archivo. La estación de penitencia articula devoción, disciplina y memoria compartida en el barrio y en la ciudad.</figcaption>
</figure>
<p>En <strong>enero de 1986</strong> llega el decreto que aprueba los Estatutos. La <strong>Peña de Costaleros</strong> nace en abril de 1986. La Diócesis, ante la Junta de Hermandades, cuestiona la salida en Jueves Santo 1985 por la saturación de cofradías; la hermandad negocia itinerarios y sentido penitencial. Se encarga el <strong>paso de misterio a Francisco Bailac</strong> —líneas rectas, gran peso— adaptado al dintel del templo. Hernández León remata la Verónica y, más tarde, Cirineo. Los cultos cuaresmales ganan solemnidad; las salidas amplían recorrido y, en 1989, la cofradía hace por primera vez <strong>estación al templo de la Patrona y carrera oficial</strong>, con ruedas para el paso y banda de Scouts. Se sustituye el <strong>escudo</strong> con óvalo, corona de espinas y sudario; en 1990 llegan las <strong>primeras medallas corporativas</strong>.</p>
<p>La devoción a <strong>María Santísima de la Salud</strong> —titular del Jueves Santo en la etapa narrada— se refuerza con nueva <strong>parihuela y cuadrilla de mujeres</strong>, estreno de mesa, incorporación del costal años después y cambios en la indumentaria procesional (terciopelo blanco, encajes, corona). La <strong>Banda de Cornetas y Tambores del Sagrado Corazón</strong> y otras formaciones acompañan ya el desfile. Los <strong>decretos de 1990</strong> amplían derechos de las mujeres en la hermandad, con matices sobre la junta hasta el cabildo de 1996. La <strong>VIII Semana Cultural</strong> cierra etapa; nuevos Estatutos se aprueban en 1991. Los años siguientes combinan estabilidad, rifas, excursiones y creciente devoción ciudadana.</p>
<h2>Cartel oficial, taller de bordados, palio y Casa de Hermandad (1994–1998)</h2>
<p>En <strong>1994</strong> la hermandad protagoniza el <strong>cartel oficial de Semana Santa</strong>: obra de <strong>Pepe Gallego</strong> a partir de fotografías de Gabriel Solís Carvajal, con el Señor y la Virgen y la fachada parroquial. Se impulsan el <strong>taller de bordados</strong> —dirigido por Antonia Gil—, restauración del estandarte y, desde 1994–1995, <strong>Misas de Hermandad</strong> mensuales. El <strong>palio</strong> para la Salud, diseñado por Ramón León Peñuelas, y las nuevas <strong>túnicas de nazareno</strong> marcan la década. En <strong>1998</strong> estrena palio y túnicas; <strong>Chiclana</strong> acompaña musicalmente al Señor; la Virgen sale bajo palio pese a la lluvia en un Jueves Santo difícil; se avanza en la <strong>Casa de Hermandad</strong>. El cambio de párroco en 1998 abre una etapa más dura.</p>
<h2>Crisis de 1999, junta gestora y normalidad procesional</h2>
<p>En <strong>1999</strong> tensiones internas y decisiones de gobierno desembocan en ceses, comunicados al barrio y en la intervención de la Diócesis: <strong>junta gestora</strong> presidida por Carlos Granja, con director espiritual el diácono Lucio Victorino Osta, hasta recomponer el rumbo. Pese a ello, la <strong>estación de penitencia del Jueves Santo 1999</strong> mantiene el cortejo en la calle con un itinerario oficial amplio. En los años siguientes la gestora y los hermanos reordenan cargos, boletines y cultos; la Virgen de la Salud sigue saliendo en Rosario por San Pedro. La documentación de algunos años es escasa, pero la memoria cofrade subraya la capacidad de la corporación para <strong>sobrevivir a la adversidad</strong> sin romper el vínculo con el barrio ni con el Obispado.</p>
<h2>Epílogo: una hermandad de barrio, Iglesia y ciudad</h2>
<figure class="historia-foto">
<img src="/assets/img/historia/hermandad-hoy.jpg" alt="Comunidad y tradición, imagen de archivo" loading="lazy" decoding="async" />
<figcaption>Imagen de archivo. La hermandad prolonga hoy el mismo impulso: fe, servicio al vecindario y transmisión de la tradición a las nuevas generaciones.</figcaption>
</figure>
<p>De la joyería de San Pedro a los templos, traslados desde Sevilla, primeras túnicas crema y morado, cartel, palio, taller de bordados, escudo y medallas, la historia condensa <strong>decenios de trabajo anónimo</strong>: cofrades, costaleros y costaleras, directores espirituales, imagineros, músicos, comerciantes y familias que pagaron cuotas, rifas y postulaciones. La Hermandad de <strong>Jesús del Perdón</strong> y <strong>María Santísima de la Salud</strong> —en la línea evolutiva narrada en la crónica— encarna la vocación de <strong>La Línea de la Concepción</strong> por una Semana Santa penitencial, social y profundamente arraigada en <strong>San Pedro</strong>. Este texto es un resumen web; los detalles cronológicos, cifras y actas completas pueden consultarse en la documentación oficial y en el libro de historia de la corporación.</p>
HTML
        ,
        'en' => <<<'HTML'
<h2>Origins in the San Pedro neighbourhood (1982–1983)</h2>
<figure class="historia-foto">
<img src="/assets/img/historia/decada-1980.jpg" alt="Urban setting, archival black and white photo" loading="lazy" decoding="async" />
<figcaption>Archival image. The brotherhood grew from dialogue between neighbours, local business and the parish in a quarter that sought stronger community and social support.</figcaption>
</figure>
<p>This page summarises the chronicle and minutes that tell how the brotherhood was born around <strong>San Pedro parish</strong>. The seed appears in Santa Isabel street, but in <strong>Martín Franco’s jeweller’s shop</strong> on San Pedro street (<strong>1982</strong>) the idea of a neighbourhood cofradía takes shape. Manuel Guerrero, Father <strong>Galindo</strong> and José Serván discuss neglect and social need, inspired by other improvement projects. The parish priest demands bringing <strong>neighbours closer to the Church</strong>. Meetings produce a committed group —including María del Carmen Rubira, Martín Franco, Antonio Rubira Urbano, José Serván, Pedro Olmo Morales, Francisco Trujillo and Manuel Guerrero— and a team of 22 people with religious, social and cultural aims.</p>
<p>On <strong>Holy Thursday 1983</strong> the Lord of Gran Poder was to visit for the parish passion play; a broken stretcher prevented entry, yet the decorated barrio kept the desire for its own procession. After Holy Saturday talks with Father Galindo, on <strong>4 April 1983</strong> Manuel Guerrero Sigler’s manuscript fixes founding bases with the parish priest and founders. The <strong>Gabaldón family</strong> deposits a sorrowful Virgin; the title moves toward <strong>Jesus del Perdón</strong> and a Marian dedication, with diocesan approval on <strong>3 June 1983</strong>. A managing board is formed, quotas begin, 10,000 holy cards are printed, and the parish council sets strict penitential rules for the first outing: night procession, Rosary, no music, austerity.</p>
<h2>First cult, cultural week and commissioning the Lord (1983–1985)</h2>
<figure class="historia-foto">
<img src="/assets/img/historia/parroquia-barrio.jpg" alt="Church and streets, archival photo" loading="lazy" decoding="async" />
<figcaption>Archival image. Worship, solidarity and street procession remain the three poles of brotherhood life.</figcaption>
</figure>
<p>The first <strong>cultural week</strong> (October 1983) includes Bishop <strong>Antonio Dorado Soto</strong>; the <strong>Dolorosa de San Pedro</strong> is blessed; a blue velvet mantle with gold lace is made. On <strong>15 September 1983</strong> she processes at dawn. In 1984 brothers vote for <strong>Manuel Hernández León’s</strong> model for <strong>Christ of Mercy in his third fall</strong> with Veronica and Simon; contracts and neighbourhood fundraising follow. The young group drives social work (over <strong>70&nbsp;% of spending</strong>). On <strong>23 March 1985</strong> the image is blessed; on <strong>2 April 1985</strong>, Holy Thursday, the first penitential procession sets out with cream tunics, purple masks, esparto belts, a rough guide cross and drums only — and rain. The brotherhood issues its <strong>first Holy Week poster</strong> and sends statutes to the diocese; the pro-cult board is authorised in July 1985.</p>
<h2>Statutes, float, growth (1986–1993)</h2>
<figure class="historia-foto">
<img src="/assets/img/historia/procesion.jpg" alt="Procession, archival black and white" loading="lazy" decoding="async" />
<figcaption>Archival image. Penitential station knits devotion, discipline and shared memory.</figcaption>
</figure>
<p>Decrees approve statutes in 1986; the <strong>costaleros’ guild</strong> is founded. The diocese questions the Holy Thursday slot; a heavy new <strong>mystery float by Francisco Bailac</strong> fits the church doorway. In 1989 the brotherhood reaches the patroness church and official route; the <strong>shield</strong> is renewed (oval, crown of thorns and shroud); <strong>corporate medals</strong> arrive in 1990. Devotion to <strong>Our Lady of Health</strong> grows with a women’s carrying team, new platforms and later the palio. Decrees in 1990 and 1996 widen women’s rights, including governance. In <strong>1994</strong> the brotherhood supplies the official Holy Week poster painted by <strong>Pepe Gallego</strong> from photographs by Gabriel Solís Carvajal.</p>
<h2>Embroidery workshop, palio, house and trials (1994–1999)</h2>
<p>The <strong>embroidery workshop</strong> led by Antonia Gil, monthly brotherhood Masses, new Nazarene tunics and <strong>Ramón León Peñuelas’s</strong> palio design mark the late 1990s. In <strong>1998</strong> Our Lady processes under canopy despite heavy rain; work begins on the <strong>brotherhood house</strong>. After a parish change in 1998, <strong>1999</strong> brings internal crisis, diocesan intervention and a <strong>stewardship board</strong> under Carlos Granja with deacon Lucio Victorino Osta; nonetheless the <strong>Holy Thursday 1999</strong> procession still takes place along a long official route. Later years restore stability, bulletins and devotion; Our Lady of Health continues her rosary through San Pedro.</p>
<h2>Closing</h2>
<figure class="historia-foto">
<img src="/assets/img/historia/hermandad-hoy.jpg" alt="Community, archival image" loading="lazy" decoding="async" />
<figcaption>Archival image. Today the brotherhood continues the same calling: faith, service to the neighbourhood and handing tradition on.</figcaption>
</figure>
<p>From the jeweller’s shop to Sevilla journeys, first cream and purple habits, posters, palio, embroidery, shield and medals, the story is decades of often anonymous work: brothers, bearers, chaplains, sculptors, musicians and families who paid dues and raffle tickets. This web summary condenses the book of history; full dates, figures and minutes belong in the corporation’s official archive and publications.</p>
HTML
        ,
    ],
];
