<?php

return [
    'title' => [
        'es' => 'Paso Ntra. Sra. de la Salud',
        'en' => 'Float of Our Lady of Health',
    ],
    'content' => [
        'es' => <<<'HTML'
<h2>El paso de María Santísima de la Salud</h2>
<p>El <strong>paso de palio</strong> de <strong>María Santísima de la Salud</strong> cierra con dignidad mariana la estación de penitencia de la Hermandad del Perdón en <strong>La Línea de la Concepción</strong>, corporación que articula en un solo misterio de fe la devoción al Cristo del Perdón y el consuelo materno de la Virgen. En la salida del <strong>Jueves Santo</strong>, el paso de la Salud recorre las calles como signo de esperanza y de cercanía a quien sufre: la Madre aparece como refugio espiritual del barrio y como custodia silenciosa del camino penitencial de sus hijos cofrades.</p>
<h2>La imagen titular</h2>
<p>La talla de la <strong>Virgen de la Salud</strong> es obra del imaginero sevillano <strong>Manuel Hernández León</strong>, realizada en <strong>1987</strong> y bendecida en la primavera de ese mismo año, en continuidad artística con el paso del Señor que la hermandad había estrenado pocos años antes. Se trata de una dolorosa de factura <strong>candelero</strong>, concebida para ser contemplada en altura y en movimiento, con una expresión de duelo contenido que evoca la compasión y la intercesión. Según la tradición cofrade que documentan las crónicas locales, la escultura se labró en <strong>madera de cedro</strong> y destaca por la serenidad del rostro y el detalle lagrimal, signo piadoso de la Virgen compartícipe en el dolor redentor de su Hijo.</p>
<h2>Palio, bordado y orfebrería</h2>
<p>El conjunto procesional combina <strong>orfebrería</strong> y <strong>textil</strong> en un lenguaje visual sobrio y noble. El palio y los paños laterales suelen presentar <strong>terciopelo marfil</strong> trabajado con bordados en hilos de oro, plata y sedas de color, en línea con la estética renacentista que enmarca la imagen y refuerza la lectura teológica de la Reina de los Ángeles bajo dosel. Los <strong>faroles</strong>, <strong>jarrón</strong> y demás piezas de metalistería ordenan el espacio del anda, acogen la luz de los cirios y contribuyen al brillo ceremonioso propio de la Madre del Redentor. En el frente del paso, la hermandad ha dispuesto históricamente <strong>relicarios</strong> vinculados a <strong>San Pedro Apóstol</strong> y a <strong>Santa Ángela de la Cruz</strong>, enlazando el patrón del templo con figuras de especial devoción en la vida de la corporación.</p>
<h2>La salida procesional y el exorno floral</h2>
<p>En la calle, el paso de la Salud avanza al ritmo de la cuadrilla de <strong>costaleras</strong> y del acompañamiento musical, en diálogo con el silencio y las oraciones del cortejo nazareno. La <strong>exornación floral</strong> tiende a combinaciones en <strong>blanco y azul celeste</strong>, colores que aluden a la pureza mariana y a la espiritualidad serena de la titular, sin renunciar a la sobriedad que pide el carácter penitencial del día. Cada Semana Santa, el equipo de cultos y el mayordomo coordinan criterios para que la flor, el encaje y la luz armonicen con el palio y con la imagen, evitando el artificio que desvirtúe el sentido litúrgico del desfile.</p>
<h2>Conservación y memoria cofrade</h2>
<p>El mantenimiento del paso —limpieza de metales, revisión de enseres, cuidado del bordado y del palio— es responsabilidad compartida entre la Junta de Gobierno, la comisión de enseres y los hermanos que custodian el patrimonio en la <strong>Parroquia de San Pedro Apóstol</strong>. Cualquier intervención debe hacerse con asesoramiento técnico y respeto a la identidad artística dejada por Hernández León. Esta página puede completarse con fotografías del paso en la <strong>galería</strong> (panel de administración) y con notas sobre restauraciones o estrenos de enseres, de modo que la web sea un archivo vivo y veraz del palio de la Salud en La Línea.</p>
HTML,
        'en' => <<<'HTML'
<h2>The float of Mary Most Holy of Health</h2>
<p>The <strong>canopy float</strong> of <strong>Mary Most Holy of Health</strong> brings the Marian dignity of the Brotherhood of the Perdón in <strong>La Línea de la Concepción</strong> to a close: one faith-mystery uniting devotion to the Christ of Mercy and the Mother’s comfort. On <strong>Maundy Thursday</strong> the Health float moves through the streets as a sign of hope and closeness to those who suffer: the Mother appears as the neighbourhood’s spiritual refuge and as silent guardian of her penitent children’s way.</p>
<h2>The titular image</h2>
<p>The statue of the <strong>Virgin of Health</strong> is the work of the Seville sculptor <strong>Manuel Hernández León</strong>, carved in <strong>1987</strong> and blessed that spring, in artistic continuity with the Lord’s float the brotherhood had introduced shortly before. It is a <strong>candelero</strong> sorrowful Virgin, meant to be seen raised and in motion, with restrained grief evoking compassion and intercession. Local cofrade accounts describe <strong>cedar wood</strong> carving, a serene face and tear detail as a sign of the Virgin’s sharing in her Son’s redeeming sorrow.</p>
<h2>Canopy, embroidery and metalwork</h2>
<p>The ensemble blends <strong>metalwork</strong> and <strong>textiles</strong> in a noble visual language. The canopy and side hangings often use <strong>ivory velvet</strong> with embroidery in gold, silver and coloured silk threads, in a Renaissance-inspired frame that supports the theology of the Queen of Angels beneath a dais. <strong>Lanterns</strong>, <strong>vases</strong> and other silverwork structure the float, hold candlelight and add the ceremonial gleam proper to the Mother of the Redeemer. On the front, the brotherhood has traditionally placed <strong>reliquaries</strong> linked to <strong>St Peter the Apostle</strong> and <strong>St Angela of the Cross</strong>, tying the parish patron to devotions dear to the corporation.</p>
<h2>The procession and floral display</h2>
<p>In the street the Health float moves to the rhythm of the <strong>female bearer team</strong> and the band, in dialogue with silence and the nazareno court’s prayer. <strong>Floral decoration</strong> tends toward <strong>white and sky blue</strong>, colours suggesting Marian purity and the titular’s serene spirituality, without betraying the day’s penitential tone. Each Holy Week, worship and steward teams align criteria so flowers, lace and light harmonise with canopy and image, avoiding display that would distort the procession’s liturgical sense.</p>
<h2>Conservation and living memory</h2>
<p>Upkeep—metal cleaning, furnishings checks, care of embroidery and canopy—is shared by the Governing Board, furnishings commission and brothers who guard heritage at <strong>St Peter’s parish</strong>. Interventions need technical advice and respect for Hernández León’s artistic identity. This page can grow with photographs in the admin <strong>gallery</strong> and notes on restoration or new pieces, so the site becomes a living, accurate record of the Health canopy in La Línea.</p>
HTML,
    ],
];
